### ISSUE TITLE
Menu size/alignment issue in mobile view

### ISSUE THREAD

**Issue by glenthomas** [nbarrett/ngx-ramblers#7]
Hi @nbarrett,

A couple of group members have shown me this issue that we have with our site's menu when displayed on mobile device dimensions.

When logged in it works fine, everything is displayed well.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/6259c605-cc01-4147-a7fb-3650bbe04e5f">

When logged out, the text in the login link pushes the menu width wider than the screen dimensions.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/05be84bf-c1e8-4ae8-aefe-e4179b9873fd">

The menu can then be dragged from side to side, leaving a blank space at the top.

<img width="501" alt="image" src="https://github.com/user-attachments/assets/8f4610d5-a388-4b5c-8167-40fcecbbe6b0">

I'm not sure what would be the best way to resolve this.

Part of the solution could be to reduce the amount of text; "Login to Stag Walkers" or "Login to Site". Code is [here](https://github.com/nbarrett/ngx-ramblers/blob/2f181a8e322a91e6b54e56ff77d1d581e35156bb/projects/ngx-ramblers/src/app/login-panel/login-panel.component.ts#L56). I expect the current text is designed to make it clear that the user is not logging in to the official Rambler's website and you would want to keep that.

Something else I have played around with is reducing the font size on mobile. I appreciate this might affect the usability of the site.

<img width="499" alt="image" src="https://github.com/user-attachments/assets/3f82b76b-23b3-4892-8a4f-2009e2868e2b">

Something else we could try is reducing the left and right margins around the login + forgot password links on mobile.

<img width="461" alt="image" src="https://github.com/user-attachments/assets/ef32a6a5-20b3-48d8-8914-b549738a21a5">

Let me know what you think. I'm happy to have a go at creating a pull request if that helps. Thanks!

**Comment by glenthomas** [comment]
Another option could be to stack the links vertically rather than horizontally. This could allow for it to accommodate more text without messing around with other aspects of the site. I did this by disabling `display: flex` on the containing div element. I think you could add `display: block` to the [.login-text style](https://github.com/nbarrett/ngx-ramblers/blob/2f181a8e322a91e6b54e56ff77d1d581e35156bb/projects/ngx-ramblers/src/app/login-panel/login-panel.component.sass#L3)

<img width="498" alt="image" src="https://github.com/user-attachments/assets/73435fd7-a7d0-4f1b-bd28-941452bbc8b2">

**Comment by nbarrett** [comment]
Hi @glenthomas - thanks for raising this - good spot. The mobile view definately needed a bit of love in this area so thanks for your suggestion which has been incorporated in [29ad8c8](https://github.com/nbarrett/ngx-ramblers/commit/29ad8c85dc0b7fa81e526e6276447aacecabaabe). Hopefully this addresses edge-cases?

**Comment by glenthomas** [comment]
Thanks @nbarrett that is now working perfectly I think. Thanks for getting that fixed so quickly!
